language: node_js

before_install:
  - npm install -g bower
  - npm install -g tsd
  - npm install -g gulp-cli

before_script:
  - bower install
  - tsd install
  - gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - node_modules
    - bower_components
    - typings