language: node_js

before_install:
  - npm install -g bower

before_script:
  - bower install
  - npm run build
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  # the environment variable CODECLIMATE_REPO_TOKEN is configured in travis
  - node_modules/.bin/codeclimate-test-reporter < coverage/Firefox*/lcov.info

cache:
  directories:
    - node_modules
    - bower_components

addons:
  firefox: "40.0"
